version: '3'
services:
  ### PHP-FPM Container
  php-fpm:
    build: ./build/php-fpm
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    links:
      - mysql
    networks:
      ordernet:
        ipv4_address: 172.21.0.6
  
  ### NGINX Container
  nginx:
    build: ./build/nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm
    networks:
      ordernet:
        ipv4_address: 172.21.0.2

  ### MySQL Container
  mysql:
    build: ./build/mysql
    volumes:
      - /var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
      ordernet:
        ipv4_address: 172.21.0.3

  ### Application Code Container
  application:
    build: ./build/application
    networks:
      ordernet:
        ipv4_address: 172.21.0.4

  ### Workspace Utilities Container
  workspace:
    build: ./build/workspace
    volumes:
      - ./:/var/www
    links:
      - mysql
    tty: true
    networks:
      ordernet:
        ipv4_address: 172.21.0.5

volumes:
  src:

networks:
  ordernet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
